name: build-and-deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/liontech-os:latest
            ghcr.io/${{ github.repository_owner }}/liontech-os:${{ github.sha }}

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy over SSH using docker compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script_stop: true
          script: |
            set -e
            # Login to GHCR on remote
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

            # Ensure app directory exists and repo is present
            mkdir -p ${{ secrets.SERVER_APP_DIR }}
            cd ${{ secrets.SERVER_APP_DIR }}

            # Pull latest image and restart
            docker compose pull
            docker compose up -d

            # Optional: show container status
            docker ps --filter "name=app" --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"